version: '3.8'

services:
  db:
    build: ./mysql/
    image: mysqlcompose
    container_name: mysqlcompose
    restart: always
    env_file:
      - ./config/db.env
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - noderednetwork

  nodered:
    depends_on:
      - db
    image: nodered/node-red
    container_name: noderedcompose
    restart: always
    ports:
      - "1880:1880"
    volumes:
      - ./node-red:/data
    networks:
      - noderednetwork

volumes:
  db_data: {}
  node-red:
    external: true

networks:
  noderednetwork:
    driver: bridge